extractor:
  tasks: 8000
  time: "10:00:00"
  mem_per_cpu_gb: 2
  randomize_start_duration: 180

minhash:
  hash_config:
    hash_fc: "sha1"
    precision: 64
  num_buckets: 14
  hashes_per_bucket: 8
  n_grams: 5

mh1:
  tasks: 1000
  time: "05:00:00"

mh2:
  tasks: 1  # Actually set automatically based on num buckets * 50
  time: "02:00:00"
  mem_per_cpu_gb: 4
  cpus_per_task: 3
  randomize_start_duration: 180

mh3:
  tasks: 1
  time: "30:00:00"
  mem_per_cpu_gb: 25
  cpus_per_task: 8

mh4:
  tasks: 1000
  time: "05:00:00"
  mem_per_cpu_gb: 4
